[package]
name = "netmon"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "netmon"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
egui = { workspace = true }
eframe = { workspace = true }
egui_plot = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
nix = { workspace = true }
libc = { workspace = true }
pcap = { workspace = true }
capture = { path = "../capture" }
resolver = { path = "../resolver" }
aggregator = { path = "../aggregator" }
controller = { path = "../controller" }
